name: Build Team Notebook

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate LaTeX file
        run: python generator.py

      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont

      - name: Compile LaTeX to PDF (Pass 1)
        continue-on-error: true
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notebook_generated.tex
          compiler: xelatex

      # Ensure pages and index is generated correctly
      - name: Compile LaTeX to PDF (Pass 2)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notebook_generated.tex
          compiler: xelatex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Team-Notebook
          path: notebook_generated.pdf